language: ruby
  rvm:
  - 2.3.4
deploy:
  provider: heroku
  api_key:
    secure: Q5THwa++Pl1oQxnGO5NNRS60316tgczkc/VBz5t3rrko1nV/RoeYUumuG9B/MlJxg9lngA/dVblMOD+LpSMwYdZI4YF8rW8ehy7WcNSNNLtdiAsZW2y5zFsW6bMyBDfG9ZUB+tXQDEwWsozbU9op3CS9IaMDvPTvajWavEGQisukgwViYfJOMJ10JfkpmVbwc6QtZydHaEeCijBT5OHFNFbUp58Qlnkx2ZHjKxvQUVAgi2Q9dP3WyCylWT8pUiCwaN+uJDE97Ybh0GZs/IImycunGau71gsyqWjmqEXCW4+H0FaOKk351DEUddS/PzNVo1PyLtEzBUcZD9u/5PWoQYRQomz3qSn8zk6FI9EGunHed80EITNUQCQEi0fXWcOksLolW/GCouOJ24yt5VqldIiMhcLYzhHMpX+fzlj7QE+enbDnxd8+4PqHt7q8vHqCKRh/pzgWoEIyOsUvZ3ez++hsm6jJQtDy5HKwbKiLTke85ed7gOTbwGMcZyqT5hFDqhB0ZgYXFyouSHSVXQ/Nhqo2XcdXtApQ9+6laTBbJMh8RHmdaciwFjRKnhgEytjzBE6Bmq7q4OAqbEWBdbT2kdfCSyDGDAheL7CgDawltS4ZvRRwPHVATtfN3xfECgTgTcdud4sEQXta8XNWO00VbQz0KvG2d9eE7GAwYQynflo=
  app: projetwilliam
  on:
    repo: wdjousse/projet2
