language: ruby
rvm:
  - 2.3.4
deploy:
  provider: heroku
  api_key:
    secure: q3b/zrcbJtsVJw28fV7k+S2DxVitLxK4P27SiL6OMcLssuVh+Bb5jzM2J08SAM7pD/I1zLzbUqm0JTkuiS+e8S0BVGSR0Qxu6tGh1xt/u2kmSTKrICN7kU1i64XTs5WV38/moliHS2vMNGy7NddJ88jokv9EhHraJdPRDmM99pDPG9fjtp1mwPVCxiy1brbUOHJDwDI5uqS9G70DzhS+9urXRXTIm3jlzaMZRDcVcHK+8R2RuMmz1FiHsw30GThb3b9RJ9McRMNmBhXWztCJAGVizDaZGIwMUqb/Cmz4/sV7x7So13c54/8FK/5/MVqO4zAmYfbrMKoTgvL2zL5OkWP1QmY3WIAqOEimwkUud5SnUz27UKl/zr41VuO34rAscou0IyZpGYIJzkRgA4IKHt1pD9z7wVTkPapWQaXuMMPEnx0ekzONuHOVNNPzTMpN04cyjYmghSwPmy2HFfL3nV8tWMhrwotKQ4AaNvvwhcagBnUQbYpD6CNhv5ZdseeS4o0ddc8AY8Ljo0VgsGYYFUQ4ZFDqdchP1k0P5ulFrt66Xcoi9nEmOmHYu5w779+K2bJ5tLNm5tdTyBNBfItb9uO3Gvoga5+2ZNieNuXn7OYGkPrfj66UYol0UDue37DF9oM2QNuCc2mBeN9jjYGKHA8Iw5uUZuvLdV4tErwr3cA=
  app: projet2
  on:
    repo: wdjousse/projet2
